### ISSUE TITLE
Make QueryTemplate work without query defined

### ISSUE THREAD

**Issue by kraftner** [Brain-WP/Hierarchy#12]
Hierarchy falls back to just using the main query but QueryTemplate fails because it accepts `null` in `findTemplate()`and `loadTemplate()` but doesn't fall back to the main query which then fails with [`applyFilter()`](https://github.com/Brain-WP/Hierarchy/blob/0668c200209d51fe325f9b519acf922604e75f33/src/QueryTemplate.php#L136) because it needs a query.

**Comment by gmazzap** [comment]
Thanks @kraftner This has been fixed with bd5bab7. Will release 2.2.1 soon with this change.

**Comment by gmazzap** [comment]
Released [2.2.1](https://github.com/Brain-WP/Hierarchy/releases/tag/2.2.1) with fix.
