### ISSUE TITLE
I think this is supposed to be `reset($type); `

### ISSUE THREAD

**Issue by binhqx** [Brain-WP/Hierarchy#13]
Looks like this is supposed to take the first item of the `$type` array when `$type` is an array. 

https://github.com/Brain-WP/Hierarchy/blob/adb52da233e586051a577ef5eabe2c537df785d5/src/Branch/BranchPostTypeArchive.php#L53

**Comment by gmazzap** [comment]
Thanks @binhqx you right, and it has been fixed.

**Comment by binhqx** [comment]
Happy to have helped!
