### ISSUE TITLE
Add support for post templates on CPT

### ISSUE THREAD

**Issue by gmazzap** [Brain-WP/Hierarchy#15]
[Post Type Templates](https://make.wordpress.org/core/2016/11/03/post-type-templates-in-4-7/) are there since in 4.7...

**Comment by darrenjacoby** [comment]
Hi @gmazzap , first off, thanks for your work on Hierarchy.

I would like to ask if there is an eta for this to be tagged?

**Comment by gmazzap** [comment]
@darrenjacoby what I need before tagging is testing both unit and "real world" test. If you can help in any of those, I will tag sooner.

**Comment by slackday** [comment]
I have tested this with my custom post types and two different custom templates. One "normal" and one with multibyte string in filename and it works as expected. 👍 

Not sure how I can perform the unit-test so need a bit of guidance if you want me to help with that.

**Comment by darrenjacoby** [comment]
@gmazzap I can pull this onto dev-master soon of Controller, which should assist with the real world testing.

**Comment by slackday** [comment]
@darrenjacoby I couldn't find `dev-master` branch of Controller which is mentioned in some issues. But I tested with `master` as a real world test and it worked. Also on a production site.

**Comment by darrenjacoby** [comment]
Cool, that's perfect, `dev-master` is `master`

**Comment by gmazzap** [comment]
Merged and added to [2.4.0](https://github.com/Brain-WP/Hierarchy/releases/tag/2.4.0).

Closing now. Thanks @slackday @darrenjacoby

**Comment by darrenjacoby** [comment]
Thank you @gmazzap ! Have a good weekend. And thanks @slackday ! I'll get this into Controller asap.
