### ISSUE TITLE
Let "shipped" finders accept multiple file extensions

### ISSUE THREAD

**Issue by schlessera** [Brain-WP/Hierarchy#2]
The current implementations of `FolderTemplateFinder` and `SubfolderTemplateFinder` only accept one string as extension.

It would be useful to let the finder look for different extensions, so that it can check for several templating engines and fetch the first matching one it finds.

A simple solution would be to accept not only a string for `$extension`, but also an array. In case of an array, just iterate over them until a template is found or all extensions have been checked.

This goes hand in hand with #1.

**Comment by gmazzap** [comment]
Done with #4
